'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace SDEPAZ_GuateMayanTravelAgency

    Partial Public Class AgenciaTravelEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=AgenciaTravelEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Clientes() As DbSet(Of Clientes)
        Public Overridable Property Destinos() As DbSet(Of Destinos)
        Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
        Public Overridable Property Viajes() As DbSet(Of Viajes)
    
    End Class

End Namespace
