'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace SDEPAZ_GuateMayanTravelAgency

    Partial Public Class Clientes
        Public Property idCliente As Integer
        Public Property primernombreCliente As String
        Public Property segundonombreCliente As String
        Public Property primerapellidoCliente As String
        Public Property segundoapellidoCliente As String
        Public Property telefonoCliente As String
        Public Property dpiCliente As String
        Public Property iddestinoCliente As Integer
        Public Property emailCliente As String
    
        Public Overridable Property Viajes As ICollection(Of Viajes) = New HashSet(Of Viajes)
    
    End Class

End Namespace
