'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace SDEPAZ_GuateMayanTravelAgency

    Partial Public Class Destinos
        Public Property idDestino As Integer
        Public Property primernombreDestino As String
        Public Property segundonombreDestino As String
        Public Property descripcionDestino As String
        Public Property precioDestino As Integer
    
        Public Overridable Property Viajes As ICollection(Of Viajes) = New HashSet(Of Viajes)
    
    End Class

End Namespace
