'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace SDEPAZ_GuateMayanTravelAgency

    Partial Public Class Viajes
        Public Property idViaje As Integer
        Public Property idCliente As Integer
        Public Property idDestino As Integer
        Public Property descripcionDestino As String
        Public Property precioDestino As Integer
        Public Property emailCliente As String
    
        Public Overridable Property Clientes As Clientes
        Public Overridable Property Destinos As Destinos
    
    End Class

End Namespace
